json.format:
  date: yyyyMMdd
  dateTime: yyyyMMdd HH:mm

mp.openapi.schema:
  java.time.LocalDateTime : |
    {
      "name": "LocalDateTime",
      "type": "string",
      "format": "yyyyMMdd HH:ss",
      "example": "20220904 09:00",
      "description": "日時型フォーマット"
    }

jwt:
  phrass: privateSecretkey
  claim:
    issuer: your-application
    issuedAt: -1            # 発行日時[-1はnow()]（秒単位）
    exp: 60                 # 有効期限（分単位）
    allowedClockSeconds: 30 # 有効期限のズレ許容時間（秒単位）
  filter:
    enable: true

healthCheck:
  memoryHealth:
    enable: off
    memoryLiveness:
      name: memory-health-check-liveness
      method: rel # rel:相対評価 or abs:絶対評価
      threshold: 90
    memoryReadiness:
      name: memory-health-check-readiness
  otherChecks:
    #- io.extact.msa.rms.platform.core.health.SimpleReadnessCheck
    #- io.extact.msa.rms.platform.core.health.RestServersReadnessCheck
    #- io.extact.msa.rms.platform.core.health.DbReadnessCheck
  #dbReadnessCheck.pingSql: "SELECT 1"


exception.mapper.unhandle.404:
  paths: ["/favicon", "/static"]

debug.sleep:
  enable: false
  time: 500 # unit:msec
