
config_ordinal: 50
#----------------------------------
# Applications Configurations
#----------------------------------
rms:
  app.name: 未設定
  openapi:
    title: 未設定
    contact:
      name: 課外活動
      url: https://extact-io.github.io/rms-website/

#----------------------------------
# MicroProfile Configurations
#----------------------------------
mp:
  openapi:
    scan.exclude.classes: io.extact.msa.rms.platform.fw.webapi.ManagementResource

#----------------------------------
# Helidon Configurations
#----------------------------------
tracing:
  enabled: false ## デフォルトでOFFで有効化したい場合に起動パラメータもしくは環境変数で有効化設定をする

#TODO: Remove when https://github.com/helidon-io/helidon/issues/5537 is fixed
security:
  providers:
      - jwt:
          atn-token:
            verify-signature: false
          sign-token:
            outbound:
              - name: "propagate-token"
