CREATE TABLE IF NOT EXISTS person (
    id INT generated by default as identity PRIMARY KEY,
    name VARCHAR(15)
);

MERGE INTO person VALUES (1, 'name1');
MERGE INTO person VALUES (2, 'name2');
MERGE INTO person VALUES (3, 'name3');
MERGE INTO person VALUES (4, 'name4');
