# Workflow - build, publish jar to GitHub Packages for this repository(msa-rms-platform)
name: deploy-workflow

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  execute:
    uses: extact-io/msa-rms-parent/.github/workflows/deploy-job.yml@main
    with:
      repo: ${{ github.repository }}
    secrets: inherit
